name: 'Release Haskell Package'
description: 'Bumps cabal version and publishes to Hackage'
inputs:
  hackage-token:
    description: 'Hackage token secret'
    required: true
  version:
    description: 'Version that will be used for the release'
    required: true
    default: "${{ github.ref_name }}"
  work-dir:
    description: 'Where to find the cabal file'
    required: true
    default: "."
  branch:
    description: "Where to push the commit with the Cabal version bump"
    required: true
    default: "master"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Extract the version number
      uses: mad9000/actions-find-and-replace-string@1
      id: version
      with:
        source: "${{ inputs.version }}"
        find: 'v'
        replace: ''

    - name: Remove the existing tag
      uses: actions/github-script@v6
      with:
        script: |
          await github.rest.git.deleteRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "tags/${{ inputs.version }}",
          });

    - name: Bump the Cabal version
      uses: nikita-volkov/edit-cabal-version.github-action@v1.1.0
      with:
        mode: set
        set-value: "${{ steps.version.outputs.value }}"
        work-dir: "${{ inputs.work-dir }}"

    - name: Commit and tag the release
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: "${{ inputs.branch }}"
        commit_message: "Bumping .cabal to ${{ steps.version.outputs.value  }}"
        tagging_message: "{{ inputs.version }}"

    - name: Build a release tarball
      run: cd ${{ inputs.work-dir }} && cabal v2-sdist
      shell: bash

    - name: Publish to Hackage
      uses: haskell-actions/hackage-publish@v1
      with:
        # http://hackage.haskell.org/users/account-management
        hackageToken: "${{ inputs.hackage-token }}"
        packagesPath: dist-newstyle/sdist
        #docsPath: ${{ runner.temp }}/docs
        publish: true
